apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: marketflow-retireops-data
  namespace: apps
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
