apiVersion: v1
kind: Secret
metadata:
  name: marketflow-retireops-secrets
  namespace: apps
type: Opaque
stringData:
  EMAIL_SMTP_HOST: ""
  EMAIL_SMTP_PORT: "587"
  EMAIL_SMTP_USER: ""
  EMAIL_SMTP_PASSWORD: ""
  TEAMS_WEBHOOK_URL: ""
  TELEGRAM_BOT_TOKEN: ""
  TELEGRAM_CHAT_ID: ""
  SMS_PROVIDER: "mock"
  SMS_ACCESS_KEY: ""
  SMS_SECRET_KEY: ""
  SMS_SENDER_NUMBER: ""
  KAKAO_PROVIDER: "mock"
  KAKAO_API_KEY: ""
  KAKAO_SENDER_KEY: ""
  KAKAO_TEMPLATE_CODE: ""
